# Database Configuration - Added the stringtype parameter from Noam
spring.datasource.url=jdbc:postgresql://localhost:5432/enigma?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=enigma
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate Settings - Keep 'update' for your bonus tasks
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
